### ISSUE TITLE
Update to Stretch

### ISSUE THREAD

**Issue by suypportedox** [Sispheor/piclodio3#5]
Hello

i do an update to stretch and the alarms not work now .  

Have you an idea ?

**Comment by Sispheor** [comment]
No, sorry but I haven't tried to do the upgrade yet.
I had a lot of issue with Stretch on Rpi with other projects. I'll stay on Jessie for a while I think.

**Comment by suypportedox** [comment]
ok 

The Play button on the homepage not work too .

I come back to Jessie and waiting for your update :-)

**Comment by DanielChesters** [comment]
Hi,
I have the same issue. It seems that Raspbian Stretch use mpv instead of mplayer (mplayer come a symlink of mpv).
To fix this issue, I edit the line 19 of back/webapi/Utils/PlayerManager.py by :
`        mplayer_options = ['-quiet', '--input-file=/dev/stdin', '--input-terminal=no']`
I can push a pull request in some days if this is OK.

**Comment by suypportedox** [comment]
Stretch uninstall mplayer by dist-upgrade for mplayer2.
Need to reinstall the package mplayer and it works fine now.

**Comment by Sispheor** [comment]
OK, thx @suypportedox .

**Comment by Sispheor** [comment]
I close this one. And I open a new one to handle now Buster :)
